### ISSUE TITLE
dotenv 造成 os.environ.get 無效

### ISSUE THREAD

**Issue by yellowsoar** [Disfactory/Disfactory#37]
如果透過 `env` 產生一個獨立的環境，  
並加入 DISFACTORY_BACKEND_DEFAULT_DB_NAME=localhost，
然後利用 `pipenv` 啟動網站：

```
env DISFACTORY_BACKEND_DEFAULT_DB_NAME=localhost pipenv run python backend/manage.py runserver 127.0.0.1:9999
```

會得到 DISFACTORY_BACKEND_DEFAULT_DB_NAME=db 的結果：

```
Loading .env environment variables…
Performing system checks...

System check identified no issues (0 silenced).
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "db" to address: nodename nor servname provided, or not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yellowsoar/.pyenv/versions/3.7.4/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/yellowsoar/.pyenv/versions/3.7.4/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check_migrations()
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/core/management/base.py", line 453, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/yellowsoar/.virtualenvs/backend-Fw7ZN90K/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "db" to address: nodename nor servname provided, or not known
```

**Comment by yellowsoar** [comment]
因為部署 middle2 時把本機 `.env` 也 push 上去，而造成網站一直啟動失敗，刪除 .env 即可...

**Comment by stegben** [comment]
其實可以討論一下環境變數和 .env 檔的優先度，我平常 production 是都不給 .env 檔，但不確定兩者都存在的時候要哪個優先比較符合佈署習慣
